# Perfil para ejecución en EC2 mediante Docker
server.port=8080

# H2 persistente en archivo dentro del contenedor
spring.datasource.url=jdbc:h2:file:/app/data/educloud
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 para la evidencia del video
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true