spring.application.name=educloud-inscripciones

server.port=8080

spring.datasource.url=jdbc:h2:mem:educloud
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion AWS S3
aws.s3.bucket=educloud-inscripciones-2026
aws.s3.region=us-east-1
# Seguridad JWT con Azure IDaaS
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/858fc5c4-4d14-449c-988b-c3af598aca2a/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=7f9be5ee-cd08-4433-9731-57d893f2c308